checks = ["all"]
initialisms = ["ACL", "API", "ASCII", "CPU", "DNS", "EOF", "HTTP", "HTTPS", "ID", "IP", "JSON", "RAM", "RPC", "SHA", "SSH", "TCP", "TLS", "TTL", "UDP", "UID", "URI", "URL", "UTF8", "UUID", "VM", "XML"]
dot_import_whitelist = []
http_status_code_whitelist = []
